### PR TITLE
Initial module creation

### PR DESCRIPTION
**Pull request by beardedsamwise**

### CODE REVIEW

**Comment by EmileHofsink** [comment]
Love this @beardedsamwise !

Just need your review @benjaminwestern

**Comment by beardedsamwise** [comment]
@benjaminwestern bump! 

@EmileHofsink is using this at AAP atm - if there are any issues/improvements can you please sing out!

**Review by benjaminwestern — DISMISSED** [review]
LGTM as a first pass. @EmileHofsink might want to perform a further review in future considering he has now implemented this

**Comment by benjaminwestern** [comment]
> @benjaminwestern bump!
> 
> @EmileHofsink is using this at AAP atm - if there are any issues/improvements can you please sing out!

Hey @beardedsamwise can you please fix this merge issue, then re-submit the PR
image

**Review by benjaminwestern — APPROVED** [review]
LGTM!

**Pull request merged**
